<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="department.aspx.cs" Inherits="BootXtech.department" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:Panel ID="Panel1" runat="server">
        <form id="form1" >
        <fieldset style="height: 361px; width: 847px;">
            <legend>Department details</legend>Department ID:<br />
&nbsp;<asp:TextBox ID="TextDepartmentId" runat="server" Width="400px" Height="40px"></asp:TextBox>
            <br />
            Department Name:<br />
&nbsp;<asp:TextBox ID="TextDepartmentName" runat="server" Width="400px" Height="40px"></asp:TextBox>
            <br />
            Department Type:<br />
&nbsp;<asp:TextBox ID="TextDepartmentType" runat="server" Width="400px" Height="40px"></asp:TextBox>
            <br />
            <br />
            <asp:Button ID="submitBtn" runat="server" Height="44px" OnClick="submitBtn_Click" Text="Submit" Width="400px" />
            </fieldset> <!--end of fieldset-->
            &nbsp;</form> 
        <br />

        <!--submit button-->
        
            <br />
    </asp:Panel> <!--panel for both textbox and datagrid-->
    <!--below pannel contains datagrid view with CRUDE method-->
    <asp:Panel ID="Panel2" runat="server">
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="DEPARTMENTID" DataSourceID="SqlDataSource3" 
            Width="653px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True">

            <Columns>
                <asp:BoundField DataField="DEPARTMENTID" HeaderText="DEPARTMENTID" ReadOnly="True" SortExpression="DEPARTMENTID" />
                <asp:BoundField DataField="DEPARTMENTNAME" HeaderText="DEPARTMENTNAME" SortExpression="DEPARTMENTNAME" />
                <asp:BoundField DataField="DEPARTMENTTYPE" HeaderText="DEPARTMENTTYPE" SortExpression="DEPARTMENTTYPE" />
            </Columns>

        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:bootxtech3 %>" DeleteCommand=
            "DELETE FROM &quot;DEPARTMENT&quot; WHERE &quot;DEPARTMENTID&quot; = :DEPARTMENTID" InsertCommand="INSERT INTO &quot;DEPARTMENT&quot;
            (&quot;DEPARTMENTID&quot;, &quot;DEPARTMENTNAME&quot;, &quot;DEPARTMENTTYPE&quot;) VALUES (:DEPARTMENTID, :DEPARTMENTNAME, :DEPARTMENTTYPE)"
            ProviderName="<%$ ConnectionStrings:bootxtech3.ProviderName %>" SelectCommand="SELECT &quot;DEPARTMENTID&quot;, &quot;DEPARTMENTNAME&quot;,
            &quot;DEPARTMENTTYPE&quot; FROM &quot;DEPARTMENT&quot;" UpdateCommand="UPDATE &quot;DEPARTMENT&quot; SET &quot;DEPARTMENTNAME&quot; 
            = :DEPARTMENTNAME, &quot;DEPARTMENTTYPE&quot; = :DEPARTMENTTYPE WHERE &quot;DEPARTMENTID&quot; = :DEPARTMENTID">
            <DeleteParameters> 
                <asp:Parameter Name="DEPARTMENTID" Type="Decimal" />
            </DeleteParameters>
            <InsertParameters> 
                <asp:Parameter Name="DEPARTMENTID" Type="Decimal" />
                <asp:Parameter Name="DEPARTMENTNAME" Type="String" />
                <asp:Parameter Name="DEPARTMENTTYPE" Type="String" />
            </InsertParameters>
            <UpdateParameters> 
                <asp:Parameter Name="DEPARTMENTNAME" Type="String" />
                <asp:Parameter Name="DEPARTMENTTYPE" Type="String" />
                <asp:Parameter Name="DEPARTMENTID" Type="Decimal" />
            </UpdateParameters>
        </asp:SqlDataSource>
        </asp:Panel>
</asp:Content>
