    <%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Student.aspx.cs" Inherits="BootXtech.Student" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:Panel ID="Panel1" runat="server" Height="457px"> <!--first panel-->
        <form id="form1" > <!--creating form-->
        <fieldset style="height: 593px; width: 301px;">
            <legend>Student information:</legend>Student ID:<br />
&nbsp;<asp:TextBox ID="TextStudentId" runat="server" Width="400px" Height="40px"></asp:TextBox> <!--text box-->
            <br />
            Student Name:<br />
&nbsp;<asp:TextBox ID="TextStudentName" runat="server" Width="400px" Height="40px"></asp:TextBox>
            <br />
            Address:<br />
&nbsp;<asp:TextBox ID="TextAddress" runat="server" Width="400px" Height="40px"></asp:TextBox>
            <br />
            Contact:<br />
&nbsp;<asp:TextBox ID="TextContact" runat="server" Width="400px" Height="40px"></asp:TextBox>
            <br />
            Email:<br />
&nbsp;<asp:TextBox ID="TextEmail" runat="server" Width="400px" Height="40px"></asp:TextBox>
            <br />
            DOB:<br />
&nbsp;<asp:TextBox ID="TextDob" runat="server" Width="400px" Height="40px"></asp:TextBox>
            <br />
            <asp:Button ID="submitBtn" runat="server" Text="Submit" Height="44px" Width="400px" OnClick="submitBtn_Click" />
            <!--submit button-->
             </fieldset>
            </form>
    </asp:Panel>
    <!--below pannel contains datagrid view with CRUDE method-->
    <asp:Panel ID="Panel2" runat="server">
       <asp:GridView ID="dataGridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" DataKeyNames="STUDENTID" 
           DataSourceID="SqlDataSource2" Height="16px" Width="837px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
           AutoGenerateSelectButton="True">
                <Columns>
                    <asp:BoundField DataField="STUDENTID" HeaderText="STUDENTID" ReadOnly="True" SortExpression="STUDENTID" />
                    <asp:BoundField DataField="STUDENTNAME" HeaderText="STUDENTNAME" SortExpression="STUDENTNAME" />
                    <asp:BoundField DataField="STUDENTADDRESS" HeaderText="STUDENTADDRESS" SortExpression="STUDENTADDRESS" />
                    <asp:BoundField DataField="STUDENTCONTACT" HeaderText="STUDENTCONTACT" SortExpression="STUDENTCONTACT" />
                    <asp:BoundField DataField="STUDENTEMAIL" HeaderText="STUDENTEMAIL" SortExpression="STUDENTEMAIL" />
                    <asp:BoundField DataField="STUDENTDOB" HeaderText="STUDENTDOB" SortExpression="STUDENTDOB" />
                </Columns>
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:bootxtech2 %>" 
                DeleteCommand="DELETE FROM &quot;STUDENT&quot; WHERE &quot;STUDENTID&quot; = :STUDENTID" InsertCommand=
                "INSERT INTO &quot;STUDENT&quot; (&quot;STUDENTID&quot;, &quot;STUDENTNAME&quot;, &quot;STUDENTADDRESS&quot;,
                &quot;STUDENTCONTACT&quot;, &quot;STUDENTEMAIL&quot;, &quot;STUDENTDOB&quot;) VALUES (:STUDENTID, :STUDENTNAME,
                :STUDENTADDRESS, :STUDENTCONTACT, :STUDENTEMAIL, :STUDENTDOB)" ProviderName="<%$ ConnectionStrings:bootxtech2.ProviderName %>" 
                SelectCommand="SELECT * FROM &quot;STUDENT&quot;" UpdateCommand="UPDATE &quot;STUDENT&quot; SET &quot;STUDENTNAME&quot; = :STUDENTNAME,
                &quot;STUDENTADDRESS&quot; = :STUDENTADDRESS, &quot;STUDENTCONTACT&quot; = :STUDENTCONTACT, &quot;STUDENTEMAIL&quot; = :STUDENTEMAIL,
                &quot;STUDENTDOB&quot; = :STUDENTDOB WHERE &quot;STUDENTID&quot; = :STUDENTID">
                <DeleteParameters> 
                    <asp:Parameter Name="STUDENTID" Type="Decimal" />
                </DeleteParameters>
                <InsertParameters> 
                    <asp:Parameter Name="STUDENTID" Type="Decimal" />
                    <asp:Parameter Name="STUDENTNAME" Type="String" />
                    <asp:Parameter Name="STUDENTADDRESS" Type="String" />
                    <asp:Parameter Name="STUDENTCONTACT" Type="Decimal" />
                    <asp:Parameter Name="STUDENTEMAIL" Type="String" />
                    <asp:Parameter Name="STUDENTDOB" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="STUDENTNAME" Type="String" />
                    <asp:Parameter Name="STUDENTADDRESS" Type="String" />
                    <asp:Parameter Name="STUDENTCONTACT" Type="Decimal" />
                    <asp:Parameter Name="STUDENTEMAIL" Type="String" />
                    <asp:Parameter Name="STUDENTDOB" Type="String" />
                    <asp:Parameter Name="STUDENTID" Type="Decimal" />
                </UpdateParameters>
            </asp:SqlDataSource>
    </asp:Panel>
</asp:Content>
