<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Teacher.aspx.cs" Inherits="BootXtech.Teacher" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">



    <asp:Panel ID="Panel2" runat="server" Height="545px"> 
        <!--second panel-->
        <form id="form1" >
        <fieldset style="height: 361px; width: 301px;"> 
            <!--field set for height and width-->
            <legend>Teachers information:</legend>Teacher ID:<br />
&nbsp;<asp:TextBox ID="TextTeacherId" runat="server" Width="400px" Height="40px"></asp:TextBox> 
            <!--creating textbox-->
            <br />
            Teacher Name:<br />
&nbsp;<asp:TextBox ID="TextTeacherName" runat="server" Width="400px" Height="40px"></asp:TextBox>
            <br />
Address:<br />
&nbsp;<asp:TextBox ID="TextAddress" runat="server" Width="400px" Height="40px"></asp:TextBox>
            <br />
            Contact:<br />
&nbsp;<asp:TextBox ID="TextContact" runat="server" Width="400px" Height="40px"></asp:TextBox>
            <br />
            Email:<br />
&nbsp;<asp:TextBox ID="TextEmail" runat="server" Width="400px" Height="40px"></asp:TextBox>
            <br />
            DOB:<br />
&nbsp;<asp:TextBox ID="TextDob" runat="server" Width="400px" Height="40px"></asp:TextBox>
            <br />
            <br />

            <asp:Button ID="submitBtn" runat="server" Text="Submit" Height="44px" Width="400px" OnClick="submitBtn_Click" />

            <br />
            <br />

            </fieldset>
            &nbsp;<br />
            <br />
            <br />
            <br />
        </form>
    </asp:Panel>
    <!--below pannel contains datagrid view with CRUDE method-->
&nbsp;<asp:Panel ID="Panel1" runat="server" Height="147px" Width="743px">
    <asp:GridView ID="dataGridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" DataKeyNames="TEACHERID" DataSourceID="SqlDataSource1" Height="16px" Width="16px" OnSelectedIndexChanged="dataGridView1_SelectedIndexChanged" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True">
                <Columns>
                    <asp:BoundField DataField="TEACHERID" HeaderText="TEACHERID" ReadOnly="True" SortExpression="TEACHERID" />
                    <asp:BoundField DataField="TEACHERNAME" HeaderText="TEACHERNAME" SortExpression="TEACHERNAME" />
                    <asp:BoundField DataField="TEACHERADDRESS" HeaderText="TEACHERADDRESS" SortExpression="TEACHERADDRESS" />
                    <asp:BoundField DataField="TEACHERCONTACTNO" HeaderText="TEACHERCONTACTNO" SortExpression="TEACHERCONTACTNO" />
                    <asp:BoundField DataField="TEACHEREMAIL" HeaderText="TEACHEREMAIL" SortExpression="TEACHEREMAIL" />
                    <asp:BoundField DataField="TEACHERDOB" HeaderText="TEACHERDOB" SortExpression="TEACHERDOB" />
                </Columns>
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:bootxtech1 %>" ProviderName="<%$ ConnectionStrings:bootxtech1.ProviderName %>" SelectCommand="SELECT * FROM &quot;TEACHER&quot;" DeleteCommand="DELETE FROM &quot;TEACHER&quot; WHERE &quot;TEACHERID&quot; = :TEACHERID" InsertCommand="INSERT INTO &quot;TEACHER&quot; (&quot;TEACHERID&quot;, &quot;TEACHERNAME&quot;, &quot;TEACHERADDRESS&quot;, &quot;TEACHERCONTACTNO&quot;, &quot;TEACHEREMAIL&quot;, &quot;TEACHERDOB&quot;) VALUES (:TEACHERID, :TEACHERNAME, :TEACHERADDRESS, :TEACHERCONTACTNO, :TEACHEREMAIL, :TEACHERDOB)" UpdateCommand="UPDATE &quot;TEACHER&quot; SET &quot;TEACHERNAME&quot; = :TEACHERNAME, &quot;TEACHERADDRESS&quot; = :TEACHERADDRESS, &quot;TEACHERCONTACTNO&quot; = :TEACHERCONTACTNO, &quot;TEACHEREMAIL&quot; = :TEACHEREMAIL, &quot;TEACHERDOB&quot; = :TEACHERDOB WHERE &quot;TEACHERID&quot; = :TEACHERID">
                <DeleteParameters>
                   
                    <asp:Parameter Name="TEACHERID" Type="Decimal" /> 
                </DeleteParameters>
                <InsertParameters>
                   
                    <asp:Parameter Name="TEACHERID" Type="Decimal" />
                    <asp:Parameter Name="TEACHERNAME" Type="String" />
                    <asp:Parameter Name="TEACHERADDRESS" Type="String" />
                    <asp:Parameter Name="TEACHERCONTACTNO" Type="Decimal" />
                    <asp:Parameter Name="TEACHEREMAIL" Type="String" />
                    <asp:Parameter Name="TEACHERDOB" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                 
                    <asp:Parameter Name="TEACHERNAME" Type="String" />
                    <asp:Parameter Name="TEACHERADDRESS" Type="String" />
                    <asp:Parameter Name="TEACHERCONTACTNO" Type="Decimal" />
                    <asp:Parameter Name="TEACHEREMAIL" Type="String" />
                    <asp:Parameter Name="TEACHERDOB" Type="String" />
                    <asp:Parameter Name="TEACHERID" Type="Decimal" />
                </UpdateParameters>
            </asp:SqlDataSource>
            </asp:Panel>

</asp:Content>
